apiVersion: v1
kind: Service
metadata:
  name: redis # 중요
  labels:
    name: redis-service
    app: demo-voting-app # for 그룹핑
spec:
  type: ClusterIP # 내부 서비스용
  ports:
    - port: 6379
      targetPort: 6379
  selector: # redis-pod 연결
    name: redis-pod
    app: demo-voting-app