apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    name: result-service
    app: demo-voting-app # for 그룹핑
spec:
  type: NodePort # 외부 서비스용
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005
  selector: # result-app-pod 연결
    name: result-app-pod
    app: demo-voting-app