apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    name: voting-service
    app: demo-voting-app # for 그룹핑
spec:
  type: NodePort # 외부 서비스용
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004
  selector: # voting-app-pod 연결
    name: voting-app-pod
    app: demo-voting-app