apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    tier: db-tier
spec:
  containers:
    - name: postgres
      image: postgres



#Instruction: Create a Kubernetes Pod definition file using values below:
#
#Name: postgres
#Labels: tier => db-tier
#Container name: postgres
#Image: postgres